### ISSUE TITLE
use fiber ctx.JSON()

### ISSUE THREAD

**Issue by sixcolors** [Yash294/TODO#2]
https://github.com/Yash294/TODO/blob/518aefdc7c4bafaa503c8419795a537eeea3378c/controllers/user.go#L53

use context JSON

https://docs.gofiber.io/api/ctx#json

**Comment by Yash294** [comment]
Removed the username feature entirely since it was not even needed to validate unique usernames 82a04784d8abd2d5fb705bde595633bd17c7ff2b
