### ISSUE TITLE
Never store secrets in plain text

### ISSUE THREAD

**Issue by sixcolors** [Yash294/TODO#4]
https://github.com/Yash294/TODO/blob/518aefdc7c4bafaa503c8419795a537eeea3378c/repos/user.go#L13

https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html

**Comment by Yash294** [comment]
Added password hashing using bcrypt 6ce613b4237b29dd5505fd7b90b630ea8d95ef20
