### ISSUE TITLE
postgres matching is case sensitive by default

### ISSUE THREAD

**Issue by sixcolors** [Yash294/TODO#5]
https://github.com/Yash294/TODO/blob/518aefdc7c4bafaa503c8419795a537eeea3378c/repos/user.go#L14

postgres matching is case sensitive by default

https://www.postgresql.org/docs/11/functions-matching.html

**Comment by Yash294** [comment]
I'm not too sure what you mean by this. Like I understand what you mean by case sensitive, but am I using the gorm functions wrong then?

**Comment by sixcolors** [comment]
You will allow users to make accounts 'joe' and 'Joe' and 'jOE' and 'JoE' etc. All different users correct?

**Comment by Yash294** [comment]
I see that makes sense. It would not be a good idea to have them all as different users.

**Comment by Yash294** [comment]
Resolved here 7c45699358d6b5a004bf5145bd5e9b294994388b
