### ISSUE TITLE
timing attack vulnerabilities

### ISSUE THREAD

**Issue by sixcolors** [Yash294/TODO#6]
https://github.com/Yash294/TODO/blob/518aefdc7c4bafaa503c8419795a537eeea3378c/repos/user.go#L35

https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#compare-password-hashes-using-safe-functions

**Comment by Yash294** [comment]
Used password checks given by bcrypt library 6ce613b4237b29dd5505fd7b90b630ea8d95ef20
