### ISSUE TITLE
password length should be more than 16

### ISSUE THREAD

**Issue by sixcolors** [Yash294/TODO#7]
https://github.com/Yash294/TODO/blob/518aefdc7c4bafaa503c8419795a537eeea3378c/models/user.go#L10

https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls

**Comment by Yash294** [comment]
Changed to min length 16 400a31d1928f18af8f12b166493442226c91119b
