### ISSUE TITLE
returning all users with their passwords is a bad idea

### ISSUE THREAD

**Issue by sixcolors** [Yash294/TODO#8]
https://github.com/Yash294/TODO/blob/518aefdc7c4bafaa503c8419795a537eeea3378c/repos/user.go#L54

don't think I need to provide a ref for this one :)

If you follow this through to the controller, `func GetAllUsernames(c *fiber.Ctx) error` it never scrubs the passwords from the data, you should use a Response model and map to that, where it does not include passwords.

**Comment by sixcolors** [comment]
ref https://github.com/Yash294/TODO/blob/518aefdc7c4bafaa503c8419795a537eeea3378c/controllers/user.go#L45

This is not a good idea.

**Comment by Yash294** [comment]
Whoops fixed it here haha, but I ended up removing it in a later commit anyways. f9d13dc6ddb96c6daae83f2c32bb2939ec5c56bc
